version: '2'

services:
  master:
    image: lewuathe/hadoop-master
    ports:
      - "9870:9840"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
    container_name: "master"
  layer1:
    image: lewuathe/hadoop-slave
    container_name: "layer1"
    depends_on:
      - master
    ports:
      - "9901:9864"
      - "8041:8042"
  layer2:
    image: lewuathe/hadoop-slave
    container_name: "layer2"
    depends_on:
      - master
    ports:
      - "9902:9864"
      - "8042:8042"
  layer3:
    image: lewuathe/hadoop-slave
    container_name: "layer3"
    depends_on:
      - master
    ports:
      - "9903:9864"
      - "8043:8042"